export default [
    { "year": 1982, "artist": "Michael Jackson", "title": "Billie Jean", "qr_data": "spotify:track:5ChkMS8OtdzJeqyybXgT27", "code1": "MJ-01", "code2": "82-TH" },
    { "year": 1991, "artist": "Nirvana", "title": "Smells Like Teen Spirit", "qr_data": "spotify:track:5ghIJDpPoe3CfHMGu71E6T", "code1": "NV-01", "code2": "91-NV" },
    { "year": 1975, "artist": "Queen", "title": "Bohemian Rhapsody", "qr_data": "spotify:track:3z8h0TU7syA3drc5k1gL0I", "code1": "QN-04", "code2": "75-OP" },
    { "year": 2017, "artist": "Ed Sheeran", "title": "Shape of You", "qr_data": "spotify:track:7qiZfU4dY1lWllzX7mPBI", "code1": "ES-03", "code2": "17-DV" },
    { "year": 1987, "artist": "U2", "title": "With or Without You", "qr_data": "spotify:track:6ADSaE87h8Y3Y2FdSAHHy", "code1": "U2-05", "code2": "87-JT" },
    { "year": 2003, "artist": "Beyoncé ft. Jay-Z", "title": "Crazy in Love", "qr_data": "spotify:track:5IVuqXILoxVWvWEPm82Jxr", "code1": "BY-01", "code2": "03-DL" },
    { "year": 1965, "artist": "The Rolling Stones", "title": "(I Can't Get No) Satisfaction", "qr_data": "spotify:track:2PzU4IB8Dr6mxV3lHuaG3t", "code1": "RS-04", "code2": "65-OB" },
    { "year": 1999, "artist": "Britney Spears", "title": "...Baby One More Time", "qr_data": "spotify:track:3MjUtNVVq3C8Fn0MP3zhXa", "code1": "BS-01", "code2": "99-BO" },
    { "year": 2011, "artist": "Adele", "title": "Rolling in the Deep", "qr_data": "spotify:track:1CkvWZme3pRgbzaxTsoVan", "code1": "AD-02", "code2": "11-21" },
    { "year": 1984, "artist": "Prince", "title": "When Doves Cry", "qr_data": "spotify:track:51H2y6YrNNXcy3dfc3qSbA", "code1": "PR-06", "code2": "84-PR" },
    { "year": 2012, "artist": "Gotye ft. Kimbra", "title": "Somebody That I Used to Know", "qr_data": "spotify:track:4LRPiXqCikLlN15c3yImP7", "code1": "GT-03", "code2": "12-ME" },
    { "year": 1971, "artist": "Led Zeppelin", "title": "Stairway to Heaven", "qr_data": "spotify:track:5CQ30WqJwcep0pYcV4AMNc", "code1": "LZ-04", "code2": "71-IV" },
    { "year": 1980, "artist": "Blondie", "title": "Call Me", "qr_data": "spotify:track:7HrmI242cRIh16vYUv4a3h", "code1": "BL-05", "code2": "80-AG" },
    { "year": 2008, "artist": "Lady Gaga", "title": "Poker Face", "qr_data": "spotify:track:1QV6tiMFM6fSOKOGLMHYYg", "code1": "LG-01", "code2": "08-FM" },
    { "year": 1997, "artist": "Spice Girls", "title": "Wannabe", "qr_data": "spotify:track:1Je1IMUlBXcx1Fz0WE7oPT", "code1": "SG-01", "code2": "97-SW" },
    { "year": 2015, "artist": "Mark Ronson ft. Bruno Mars", "title": "Uptown Funk", "qr_data": "spotify:track:32OlwpcMpofmOI5RSoSCqk", "code1": "MR-04", "code2": "15-US" },
    { "year": 1977, "artist": "Bee Gees", "title": "Stayin' Alive", "qr_data": "spotify:track:4UDmDIqJIbrW0hMBQMcs8k", "code1": "BG-05", "code2": "77-SN" },
    { "year": 2002, "artist": "Eminem", "title": "Lose Yourself", "qr_data": "spotify:track:5Z01UMMf7V1o0MzF86s6WJ", "code1": "EM-08", "code2": "02-8M" },
    { "year": 1985, "artist": "a-ha", "title": "Take On Me", "qr_data": "spotify:track:2WfaOiMkCvy7F5fcp2zZ8L", "code1": "AH-01", "code2": "85-HB" },
    { "year": 1994, "artist": "Mariah Carey", "title": "All I Want for Christmas Is You", "qr_data": "spotify:track:0bYg9bo50gSsH3LeXe2SQP", "code1": "MC-04", "code2": "94-MC" }
];
